### ISSUE TITLE
Does it work?

### ISSUE THREAD

**Issue by phamsarah** [s3va/Show_Nice_Hash_Stat#1]
Hi Im writing this in Kotlin and NiceHash java example on their docs doesn't even work.... just wondering if your code works?

**Comment by s3va** [comment]
The app worked two years ago. I don't know if it works now. I don't mine bitcoins anymore. Therefore, I have not used my own application for nicehash.com for a long time. The reason that prompted me to write the app is that nicehash didn't have its own app on play.google.com . I wanted to monitor the state of the farm from my smartphone. Now my farm is gone. And there is no point in writing my own application. Everything is ready from nicehash.com.
I don't know what changes have been made to the nicehash.com API in two years, if any.

**Comment by phamsarah** [comment]
@s3va Ahh... I see. Thank you for the response!
